import type { AppState, Category, KnowledgeCard, Scene } from "./types";

export const defaultCategories: Category[] = [
  { id: "linux", name: "Linux", description: "系统、网络与文件命令", color: "#287052", icon: "terminal", builtIn: true },
  { id: "git", name: "Git", description: "版本控制与协作流程", color: "#A54A34", icon: "branch", builtIn: true },
  { id: "docker", name: "Docker", description: "容器、镜像与环境维护", color: "#336FA7", icon: "box", builtIn: true },
  { id: "database", name: "数据库", description: "SQL、备份与数据维护", color: "#7558A6", icon: "database", builtIn: true },
  { id: "media", name: "媒体工具", description: "FFmpeg、ADB 与实用工具", color: "#A66A24", icon: "media", builtIn: true },
  { id: "game", name: "游戏教程", description: "单机攻略、路线与控制台代码", color: "#B04369", icon: "game", builtIn: true },
  { id: "workflow", name: "工作流程", description: "步骤、清单与个人 SOP", color: "#4E687E", icon: "checklist", builtIn: true },
];

export const defaultScenes: Scene[] = [
  {
    id: "development",
    name: "开发工作",
    description: "代码、终端与环境维护",
    categoryIds: ["linux", "git", "docker"],
    accent: "#2E7255",
    icon: "code",
    builtIn: true,
  },
  {
    id: "game-time",
    name: "游戏时间",
    description: "攻略、代码与快捷操作",
    categoryIds: ["game"],
    accent: "#A83F68",
    icon: "game",
    builtIn: true,
  },
  {
    id: "data-tools",
    name: "数据与工具",
    description: "数据库、媒体和设备工具",
    categoryIds: ["database", "media", "linux"],
    accent: "#5C58A6",
    icon: "database",
    builtIn: true,
  },
  {
    id: "daily",
    name: "日常流程",
    description: "常用步骤与个人清单",
    categoryIds: ["workflow", "linux"],
    accent: "#526E7E",
    icon: "sun",
    builtIn: true,
  },
];

const now = new Date().toISOString();

const card = (value: Omit<KnowledgeCard, "id" | "isFavorite" | "createdAt" | "updatedAt"> & { id: string; isFavorite?: boolean }): KnowledgeCard => ({
  ...value,
  isFavorite: value.isFavorite ?? false,
  createdAt: now,
  updatedAt: now,
});

export const defaultCards: KnowledgeCard[] = [
  card({
    id: "seed-linux-port",
    title: "查看 3000 端口占用",
    description: "定位占用本地开发端口的进程。",
    content: "lsof -i :3000",
    categoryId: "linux",
    sceneIds: ["development", "data-tools"],
    tags: ["端口", "进程", "网络"],
    kind: "command",
    riskLevel: "low",
    source: "内置示例",
    isFavorite: true,
  }),
  card({
    id: "seed-linux-size",
    title: "找出当前目录的大文件",
    description: "按体积从大到小列出前 20 个文件或目录。",
    content: "du -ah . | sort -rh | head -20",
    categoryId: "linux",
    sceneIds: ["development", "daily"],
    tags: ["磁盘", "文件", "清理"],
    kind: "command",
    riskLevel: "low",
    source: "内置示例",
  }),
  card({
    id: "seed-git-undo",
    title: "撤销最近一次提交，保留改动",
    description: "回退 HEAD，但让文件改动继续保留在暂存区。",
    content: "git reset --soft HEAD~1",
    categoryId: "git",
    sceneIds: ["development"],
    tags: ["撤销", "提交", "回退"],
    kind: "command",
    riskLevel: "medium",
    source: "内置示例",
    isFavorite: true,
  }),
  card({
    id: "seed-git-branch",
    title: "清理已经合并的本地分支",
    description: "先确认分支均已合并，再批量删除。",
    content: "git branch --merged | grep -v '\\*' | xargs -n 1 git branch -d",
    categoryId: "git",
    sceneIds: ["development"],
    tags: ["分支", "清理"],
    kind: "command",
    riskLevel: "high",
    source: "内置示例",
  }),
  card({
    id: "seed-docker-prune",
    title: "清理未使用的 Docker 资源",
    description: "删除未使用的镜像、容器和网络，执行前先检查环境。",
    content: "docker system prune -a",
    categoryId: "docker",
    sceneIds: ["development"],
    tags: ["镜像", "容器", "清理"],
    kind: "command",
    riskLevel: "medium",
    source: "内置示例",
  }),
  card({
    id: "seed-db-backup",
    title: "导出 PostgreSQL 数据库",
    description: "生成可用于迁移或恢复的压缩备份文件。",
    content: "pg_dump -Fc -d app_db -f app_db.dump",
    categoryId: "database",
    sceneIds: ["data-tools"],
    tags: ["PostgreSQL", "备份", "迁移"],
    kind: "command",
    riskLevel: "low",
    source: "内置示例",
  }),
  card({
    id: "seed-media-compress",
    title: "压缩视频并保留清晰度",
    description: "使用 H.264 CRF 方式压缩常见视频。",
    content: "ffmpeg -i input.mp4 -c:v libx264 -crf 23 -preset medium -c:a aac output.mp4",
    categoryId: "media",
    sceneIds: ["data-tools"],
    tags: ["FFmpeg", "视频", "压缩"],
    kind: "command",
    riskLevel: "low",
    source: "内置示例",
  }),
  card({
    id: "seed-game-route",
    title: "探索开放世界前的准备清单",
    description: "适用于进入高风险区域前的通用准备。",
    content: "1. 在安全点手动存档\n2. 补满治疗与弹药\n3. 清理背包，只保留任务必需品\n4. 标记撤离路线和最近的快速旅行点",
    categoryId: "game",
    sceneIds: ["game-time"],
    tags: ["探索", "准备", "存档"],
    kind: "guide",
    riskLevel: "low",
    source: "内置示例",
    isFavorite: true,
  }),
  card({
    id: "seed-game-code",
    title: "Minecraft 切换创造模式",
    description: "需要世界允许作弊或拥有相应权限。",
    content: "/gamemode creative",
    categoryId: "game",
    sceneIds: ["game-time"],
    tags: ["Minecraft", "控制台", "模式"],
    kind: "command",
    riskLevel: "low",
    source: "内置示例",
  }),
  card({
    id: "seed-workflow-debug",
    title: "问题排查的最短路径",
    description: "避免一开始就修改多个变量。",
    content: "复现问题 → 记录输入与环境 → 缩小到最小案例 → 一次只验证一个假设 → 修复后补回归验证",
    categoryId: "workflow",
    sceneIds: ["daily", "development"],
    tags: ["排查", "调试", "流程"],
    kind: "guide",
    riskLevel: "low",
    source: "内置示例",
  }),
];

export function createInitialState(legacyNote = ""): AppState {
  const cards = [...defaultCards];
  if (legacyNote.trim()) {
    cards.unshift(
      card({
        id: "legacy-note",
        title: "从旧版便签迁移的内容",
        description: "旧版 Command Pocket 中保存的便签。",
        content: legacyNote.trim(),
        categoryId: "workflow",
        sceneIds: ["daily"],
        tags: ["迁移", "便签"],
        kind: "note",
        riskLevel: "low",
        source: "旧版便签",
      }),
    );
  }
  return {
    version: 2,
    categories: defaultCategories.map((item) => ({ ...item })),
    scenes: defaultScenes.map((item) => ({ ...item, categoryIds: [...item.categoryIds] })),
    cards,
  };
}

